package com.alan344.mybatis.mapper;

import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.JavaVisibility;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.codegen.mybatis3.javamapper.elements.AbstractJavaMapperMethodGenerator;

import java.util.Set;
import java.util.TreeSet;

/**
 * The selectAll method is only generated by the Mybatis3Simple runtime.
 *
 * @author Jeff Butler
 */
public class SelectListMethodGenerator extends AbstractJavaMapperMethodGenerator {
    @Override
    public void addInterfaceElements(Interface interfaze) {
        Method method = new Method(introspectedTable.getSelectAllStatementId());
        method.setVisibility(JavaVisibility.PUBLIC);
        method.setAbstract(true);

        FullyQualifiedJavaType returnType = FullyQualifiedJavaType.getNewListInstance();
        FullyQualifiedJavaType listType = new FullyQualifiedJavaType(introspectedTable.getBaseRecordType());

        returnType.addTypeArgument(listType);
        method.setReturnType(returnType);

        // 添加 import
        Set<FullyQualifiedJavaType> importedTypes = new TreeSet<>();
        importedTypes.add(FullyQualifiedJavaType.getNewListInstance());
        importedTypes.add(listType);
        importedTypes.add(new FullyQualifiedJavaType("com.sy.common.bo.Query"));
        this.addImportedType(interfaze, importedTypes);

        context.getCommentGenerator().addGeneralMethodComment(method, introspectedTable);
    }

    private void addImportedType(Interface interfaze, Set<FullyQualifiedJavaType> importedTypes) {
        for (FullyQualifiedJavaType fqjt : importedTypes) {
            interfaze.addImportedType(fqjt);
        }
    }
}
